services:
  - type: web
    name: nw_backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nw_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nw_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: nw_backend.settings.production
databases:
  - name: nw_db
    ipAllowList: []
    plan: free
    region: singapore